package com.model;

/**
 * TKeshi generated by MyEclipse Persistence Tools
 */

public class TKeshi implements java.io.Serializable
{


	private Integer keshiId;
	private String keshiAnme;
	private String del;
	
	
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public String getKeshiAnme()
	{
		return keshiAnme;
	}
	public void setKeshiAnme(String keshiAnme)
	{
		this.keshiAnme = keshiAnme;
	}
	public Integer getKeshiId()
	{
		return keshiId;
	}
	
	
	public void setKeshiId(Integer keshiId)
	{
		this.keshiId = keshiId;
	}

}