package com.model;

/**
 * TLianjie generated by MyEclipse Persistence Tools
 */

public class TLianjie implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String name;

	private String url;

	private String del;

	// Constructors

	/** default constructor */
	public TLianjie()
	{
	}

	/** full constructor */
	public TLianjie(String name, String url, String del)
	{
		this.name = name;
		this.url = url;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getUrl()
	{
		return this.url;
	}

	public void setUrl(String url)
	{
		this.url = url;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}